//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBDCostTrackingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTORY()
        {
            this.MATERIAL_REQ = new HashSet<MATERIAL_REQ>();
        }
    
        public int ID { get; set; }
        public int materialID { get; set; }
        public Nullable<decimal> invAvgNet { get; set; }
        public Nullable<decimal> invList { get; set; }
        public Nullable<short> invSizeAmnt { get; set; }
        public string invSizeUnit { get; set; }
        public short invQOH { get; set; }
    
        public virtual MATERIAL MATERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAL_REQ> MATERIAL_REQ { get; set; }
    }
}
