//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBDCostTrackingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL_REQ
    {
        public int ID { get; set; }
        public int inventoryID { get; set; }
        public int projectID { get; set; }
        public Nullable<System.DateTime> mreqDeliver { get; set; }
        public Nullable<System.DateTime> mreqInstall { get; set; }
        public Nullable<short> mreqEstQty { get; set; }
        public Nullable<short> mreqActQty { get; set; }
    
        public virtual INVENTORY INVENTORY { get; set; }
        public virtual PROJECT PROJECT { get; set; }
    }
}
