//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBDCostTrackingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_TEAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROD_TEAM()
        {
            this.LABOUR_REQUIREMENT = new HashSet<LABOUR_REQUIREMENT>();
            this.PROJECTs = new HashSet<PROJECT>();
            this.TEAM_MEMBER = new HashSet<TEAM_MEMBER>();
        }
    
        public int ID { get; set; }
        public int projectID { get; set; }
        public string teamPhaseIn { get; set; }
        public string teamName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LABOUR_REQUIREMENT> LABOUR_REQUIREMENT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT> PROJECTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAM_MEMBER> TEAM_MEMBER { get; set; }
    }
}
