//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBDCostTrackingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_TOOL
    {
        public int ID { get; set; }
        public int projectID { get; set; }
        public int toolID { get; set; }
        public byte ptQty { get; set; }
        public Nullable<System.DateTime> ptDeliverFrom { get; set; }
        public Nullable<System.DateTime> ptDeliverTo { get; set; }
    
        public virtual PROJECT PROJECT { get; set; }
        public virtual TOOL TOOL { get; set; }
    }
}
