//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBDCostTrackingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TASK()
        {
            this.LABOUR_REQUIREMENT = new HashSet<LABOUR_REQUIREMENT>();
        }
    
        public int ID { get; set; }
        public string taskDesc { get; set; }
        public Nullable<byte> taskStdTimeAmnt { get; set; }
        public string taskStdTimeUnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LABOUR_REQUIREMENT> LABOUR_REQUIREMENT { get; set; }
    }
}
