//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBDCostTrackingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORKER()
        {
            this.PROJECTs = new HashSet<PROJECT>();
            this.TEAM_MEMBER = new HashSet<TEAM_MEMBER>();
        }
    
        public int ID { get; set; }
        public string wrkFName { get; set; }
        public string wrkLName { get; set; }
        public int wrkTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT> PROJECTs { get; set; }
        public virtual WORKER_TYPE WORKER_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAM_MEMBER> TEAM_MEMBER { get; set; }
    }
}
